import "dotenv/config";
import fetch from "node-fetch";

const FORMATS = [
  { type: "Infomercial", hook: "Are you tired of...", voice: "desperate, breathless, assumes the listener is suffering" },
  { type: "Luxury", hook: "For those who understand...", voice: "quiet, assured, slightly contemptuous of people who need to be told. Brief. Never explains itself. One clause per sentence." },
  { type: "Tech Startup", hook: "We rebuilt X from the ground up", voice: "a solution looking for a problem, states the obvious without thinking objectively" },
  { type: "Gov PSA", hook: "Did you know...", voice: "clear, concise, blame shifting to the reader" },
  { type: "Late Night TV", hook: "But wait, there's more", voice: "begging you not to switch off" },
  { type: "Wellness", hook: "Your body deserves...", voice: "inventing medical issues you don't have, to seed dependence" },
  { type: "Financial", hook: "Don't leave money on the table", voice: "get in early and you'll make money, don't miss out, hint at scarcity" },
  { type: "Legal", hook: "A common side effect from X is suffering from the negative impacts associated with Y", voice: "your mileage may vary, we are not responsible" },
  { type: "Real Estate", hook: "The value of properties is sky rocketing if you have your own X", voice: "tacky and obvious, mutton dressed up as lamb" },
  { type: "Job Posting", hook: "Are you an experienced X maintenance professional, looking for work in the Y industry?", voice: "genuine but oblivious" },
  { type: "Warning", hook: "TOXIC - when taken X can be harmful to your Y", voice: "worst case scenario" },
  { type: "LinkedIn", hook: "Don't count your X before they Y - trust me, i turned a startup into a 500m ARR business", voice: "delusional confidence, humble-brag disguised as wisdom" },
  { type: "Kickstarter", hook: "When you have all your X and they are out of control, you need a Y", voice: "nervous, but sure of themselves, self made bootstrap approach" },
  { type: "Supermarket", hook: "Buy now and get an extra X when you buy Y", voice: "shouty, trying to confuse the fact these are commodity items on a race to the bottom" },
  { type: "Insurance", hook: "Following a recent incident...", voice: "factual but clearly telling one side of the story" },
  { type: "Classified", hook: "FOR SALE: One careful owner...", voice: "sleazy and untrustworthy, too good to be true" },
  { type: "Pyramid Scheme", hook: "I wasn't sure at first, but...", voice: "product focused, obfuscates truth of the matter" },
  { type: "Caution", hook: "CAUTION: May cause...", voice: "nested sentences with compounding structure, unnecessarily confusing" },
  { type: "Yelp", hook: "I don't normally do this but...", voice: "grievance spiral, starts calm then deteriorates" },
];

const CONCEPTS = [
  // Geological / earth science
  "a sedimentary layer",
  "an alluvial fan",
  "a lava tube",
  "a tectonic plate boundary",
  "a glacial erratic",
  "a sinkhole",
  "a salt flat",
  "a thermal vent",
  "a limestone karst",
  "a mudflat",
  "a moraine",
  "a basalt column",
  "a fossil bed",
  "a fault line",
  "a geyser field",
  "a coral atoll",
  "a river delta",
  "a sandstone arch",
  "a volcanic caldera",
  "a permafrost layer",
  "a gravel bar",
  "a rock cycle",
  "a soil horizon",
  "an igneous intrusion",
  "a metamorphic aureole",
  "a submarine canyon",
  "a continental shelf",
  "a rift valley",
  "a magma chamber",
  "a pumice field",
  // Food and drink
  "a sourdough starter",
  "the Maillard reaction",
  "a reduction sauce",
  "a fermentation vessel",
  "a brine solution",
  "a roux",
  "a clarified butter",
  "a smoking point",
  "a mother vinegar",
  "a proofing drawer",
  "a dry rub",
  "an emulsion",
  "a consommé",
  "a mirepoix",
  "a deglazed pan",
  "a blanching process",
  "a render of fat",
  "a mise en place",
  "a laminated dough",
  "a cold brew ratio",
  "a caramelisation point",
  "a stock reduction",
  "a cure of salt and sugar",
  "a vacuum seal",
  "a water bath",
  "a tempering process",
  "a bloom of gelatin",
  "a knife bevel",
  "a mandoline setting",
  "a pressure differential in an espresso portafilter",
  "a yeast colony",
  "a whey protein",
  "a seed oil",
  "a grain ferment",
  "a barrel char",
  "a hop addition",
  "a malting floor",
  "a pectin set",
  "a fat cap",
  "a meat rest",
  // Mathematical concepts
  "a prime number",
  "an asymptote",
  "a Fibonacci sequence",
  "a null set",
  "a probability distribution",
  "a topological surface",
  "a Möbius strip",
  "a fractal boundary",
  "a vector field",
  "a polynomial root",
  "an imaginary number",
  "a Venn diagram",
  "a recursive function",
  "a graph vertex",
  "a standard deviation",
  "a logarithmic scale",
  "a Bayesian prior",
  "a convex hull",
  "a matrix determinant",
  "a Taylor series",
  "a harmonic mean",
  "a geometric proof",
  "a set intersection",
  "a differential equation",
  "a saddle point",
  "a Cartesian plane",
  "a binary tree",
  "a Fourier transform",
  "a confidence interval",
  "a hyperbolic curve",
  "an eigenvalue",
  "a statistical outlier",
  "a Boolean operator",
  "a permutation group",
  "a golden ratio",
  "a pi approximation",
  "a number line",
  "a median value",
  "a regression line",
  "a combinatorial proof",
  // Astronomical concepts
  "a stellar nursery",
  "an accretion disk",
  "a planetary nebula",
  "a dark matter halo",
  "a gravitational lens",
  "a magnetosphere",
  "a solar wind",
  "a Lagrange point",
  "an orbital resonance",
  "a stellar parallax",
  "a redshift",
  "a cosmic ray",
  "a neutron star interior",
  "a binary star system",
  "a protoplanetary disk",
  "a Kuiper belt object",
  "a coronal mass ejection",
  "a tidal locking mechanism",
  "a retrograde orbit",
  "a stellar classification",
  "a Hertzsprung-Russell diagram",
  "a light cone",
  "a gravitational wave",
  "a cosmic microwave background",
  "a stellar evolution sequence",
  "a planetary transit",
  "a perihelion passage",
  "a zodiacal light",
  "a synodic period",
  "a barycentre",
  // Architectural elements
  "a load-bearing wall",
  "a flying buttress",
  "a barrel vault",
  "a cantilever",
  "a thermal bridge",
  "a damp course",
  "a lintel",
  "a soffit",
  "a parapet",
  "a curtain wall system",
  "a post-tension slab",
  "a moment frame",
  "a shear wall",
  "a vapour barrier",
  "a structural ridge beam",
  "a foundation pile",
  "an expansion joint",
  "a grout bed",
  "a weep hole",
  "a reveal",
  "a threshold detail",
  "a column capital",
  "a spandrel panel",
  "a clerestory window",
  "a coffered ceiling",
  "a plenum space",
  "a double-skin facade",
  "a tension cable",
  "a transfer slab",
  "an acoustic baffle",
  "a datum line",
  "a setback requirement",
  "a floor-to-ceiling ratio",
  "a thermal mass",
  "a passive solar orientation",
  // Weather phenomena
  "a temperature inversion",
  "an orographic lift",
  "a sea breeze front",
  "a föhn effect",
  "a convective cell",
  "a pressure gradient",
  "a dew point",
  "an albedo effect",
  "an urban heat island",
  "a jet stream",
  "a cold front passage",
  "an anticyclonic rotation",
  "a supercooled droplet",
  "a virga",
  "a mammatus cloud",
  "a lenticular cloud formation",
  "a fog bank",
  "a hail embryo",
  "a wind shear layer",
  "a thermal updraft",
  "a squall line",
  "a mesocyclone",
  "a katabatic wind",
  "a harmattan",
  "a haboob",
  "a pea souper",
  "a radiation frost",
  "a freezing rain event",
  "a subtropical ridge",
  "a polar vortex displacement",
  // Fictional / conceptual locations
  "a liminal space",
  "a void between floors",
  "an unmapped territory",
  "a threshold between jurisdictions",
  "a disputed border zone",
  "a negative space",
  "an interstitial zone",
  "a dead letter office",
  "a buffer state",
  "a demilitarised zone",
  "a neutral ground",
  "a no man's land",
  "a transit lounge",
  "an airside zone",
  "a bonded warehouse",
  "a freeport",
  "a tax haven",
  "an extraterritorial enclave",
  "a cartographic blank",
  "a terra incognita",
  "an unincorporated area",
  "a commons",
  "a grey zone",
  "a staging area",
  "a holding pattern",
  "an anteroom",
  "a dead end",
  "a threshold",
  "an edge condition",
  "a margin",
  // Material science / physics
  "a stress fracture",
  "a yield point",
  "a fatigue cycle",
  "a tensile strength",
  "a shear modulus",
  "a coefficient of friction",
  "a thermal expansion joint",
  "a crystalline lattice",
  "a grain boundary",
  "a surface tension",
  "a capillary action",
  "a viscosity gradient",
  "a phase transition",
  "a latent heat",
  "a specific gravity",
  "a refractive index",
  "a magnetic hysteresis",
  "a Doppler shift",
  "a standing wave",
  "a resonant frequency",
  "a half-life",
  "a decay chain",
  "a fission product",
  "a plasma state",
  "a Bose-Einstein condensate",
  "a superconducting threshold",
  "a quantum tunnelling event",
  "a spin state",
  "a wave function collapse",
  "an entropy increase",
  // Biological / ecological concepts
  "a trophic cascade",
  "a keystone species role",
  "a niche partitioning",
  "a succession stage",
  "a carrying capacity",
  "a mutualistic relationship",
  "a parasite load",
  "a seed bank",
  "a mycorrhizal network",
  "a pheromone trail",
  "a courtship display",
  "a territorial boundary",
  "a migration corridor",
  "a population bottleneck",
  "a genetic drift event",
  "a horizontal gene transfer",
  "an endosymbiotic relationship",
  "a biomass pyramid",
  "a decomposition rate",
  "a nutrient cycle",
  "an osmotic pressure",
  "a cell membrane",
  "a mitotic division",
  "a protein folding",
  "an enzyme cascade",
  "an immune response",
  "an apoptosis signal",
  "a circadian rhythm",
  "a vestigial structure",
  "a convergent evolution",
  // Economic / systems concepts
  "a supply chain bottleneck",
  "a price floor",
  "a price ceiling",
  "a sunk cost",
  "a negative externality",
  "a tragedy of the commons",
  "a liquidity trap",
  "a yield curve",
  "a shadow price",
  "a deadweight loss",
  "a moral hazard",
  "a principal-agent problem",
  "a network effect",
  "a switching cost",
  "a first-mover advantage",
  "a market clearing price",
  "an opportunity cost",
  "a diminishing return",
  "a comparative advantage",
  "a prisoner's dilemma",
];

function randomConcept() {
  return CONCEPTS[Math.floor(Math.random() * CONCEPTS.length)];
}

async function getWikiArticle() {
  const res = await fetch("https://en.wikipedia.org/api/rest_v1/page/random/summary");
  if (!res.ok) throw new Error(`Wikipedia API error: ${res.status}`);
  const data = await res.json();
  return {
    title: data.title,
    summary: data.extract ? data.extract.slice(0, 300) : "",
  };
}

export async function generateAd() {
  const wiki = await getWikiArticle();
  const concept = randomConcept();
  const format = FORMATS[Math.floor(Math.random() * FORMATS.length)];

  const prompt = `You are a deranged advertising copywriter who has been given two completely unrelated subjects and must produce a fake advertisement that treats their combination as completely normal.

Subject A (from Wikipedia): ${wiki.title} — ${wiki.summary}
Subject B (a concept): ${concept}

Ad format: ${format.type}
Tone of voice: ${format.voice}
Content hook: ${format.hook}

BRAND NAME:
Invent a fake brand name that is obviously wrong — it should sound like someone fed both subjects into a name generator and hit enter without checking. Not a pun. Not a joke. Just confidently incorrect. Like a company that should not exist.

COPY RULES:
- You must include at least one specific detail from the Wikipedia subject and work the concept into the copy as if it belongs there
- The ad must go somewhere unexpected — start in format, then let the combination pull it somewhere it shouldn't go
- Never acknowledge the subjects are unrelated
- Write with the unhinged sincerity of someone who sees no problem here whatsoever
- Never use real names of living or historical people from the Wikipedia subject — refer to them only by role or category
- Never use real business names from the Wikipedia subject — refer to them by type only
- Do not use the words: revolutionary, game-changing, innovative, unlock, leverage, seamlessly
- adCopy must be under 220 characters. Front-load the most specific and wrong detail first.

OUTPUT:
1. headline — one punchy sentence in the tone of the format
2. adCopy — 2-3 sentences. Start in format voice, let it drift.
3. imageQuery — a 2-3 word Unsplash search term for a visually striking real photo

Return ONLY valid JSON, no markdown, no backticks:
{"brandName": "...", "headline": "...", "adCopy": "...", "imageQuery": "..."}`;

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 1000,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!res.ok) throw new Error(`Anthropic API error: ${res.status}`);
  const data = await res.json();
  const text = data.content[0].text.trim();
  const clean = text.replace(/^```json\s*|^```\s*|```$/gm, "").trim();
  const parsed = JSON.parse(clean);

  return {
    brandName: parsed.brandName,
    headline: parsed.headline,
    adCopy: parsed.adCopy,
    imageQuery: parsed.imageQuery,
    format: format.type,
    subjectA: wiki.title,
    subjectB: concept,
  };
}